### ISSUE TITLE
update(message) that follows start() will have message overwritten

### ISSUE THREAD

**Issue by bobojdogg** [kuuurt13/ng-block-ui#103]
Problem: In the case that you send messages to the start and update methods, you cannot rely upon the order that these methods were called. 

If the first call is to start(), it will not set the message on the component synchronously, it will do so via a setTimeout.  If you then call 'update(message)', which is synchronous, it will set the message only to have the earlier 'start' finally run from the setTimeout which will overwrite the message.

**Comment by kuuurt13** [comment]
@bobojdogg I added a fix for your issue in `ng-block-ui@2.1.6`. Please try upgrading and let me know if it fixes your specific issue. I tested it out on my end ([see here](https://stackblitz.com/edit/github-i9qstf?file=src%2Fapp%2Fapp.component.ts)) and it seems like it is working. Just let me know, thanks!

**Comment by bobojdogg** [comment]
This appears to fix the issue, thanks.

**Comment by kuuurt13** [comment]
Great, closing this issue then 👍
