### ISSUE TITLE
Non-delay instance is not working properly

### ISSUE THREAD

**Issue by benj0c** [kuuurt13/ng-block-ui#107]
BlockUI Service `start` and `stop` methods are currently call `showBlock` or `hideBlock` inside `setTimeout` even if it runs without delay. That cause some unexpected behavior if you try to do following:
```typescript
blockui.start();
this.call_api().subscribe(() => {
  blockui.stop();
  this.do_action();
});

do_action() {
  blockui.start();
  ....
}
```
Second `start` doesn't call `showBlock` method and it cause that the BlockUI component will not be shown.
 
It's happens because `onStop` method clear the state inside `setTimeout`. So, `onStart` method check conditions before that clear state called and not schedule show block method (based on conditions in moment when called). For illustration purpose here is implementation of those two methods: 
```typescript
 private onStart({ name, message }: BlockUIEvent) {
    if (name === this.name) {
      const delay = this.delayStart || this.settings.delayStart || 0;

      if (this.state.startTimeout === null) { // <<<< 2
        this.state.startTimeout = setTimeout(() => {
          this.showBlock(message); // <<<< 4
        }, delay);
      }

      this.state.blockCount++;
      this.updateInstanceBlockCount();
    }
  }

  private onStop({ name }: BlockUIEvent) {
    if (name === this.name) {
      const delay = this.delayStop || this.settings.delayStop || 0;

      if (this.state.blockCount > 1) {
        this.state.blockCount--;
      } else {
        if (!this.active) {
          this.clearState();
        } else {
          if (this.state.stopTimeout === null) {  // <<<< 1
            this.state.stopTimeout = setTimeout(() => {
              this.hideBlock(); // <<<< 3
            }, delay);
          }
        }
      }

      this.updateInstanceBlockCount();
    }
  }
```
I'm added some comments inside implementation (<<<< [number]). Those numbers represents execution order. So, `<<<<4` block will not be executed.

There is two quick solutions to fix that. First one, move conditions of `onStart` and `onStop` methods inside `setTimeout` block also. Second one, if delay equals 0, run code (`showBlock` and `hideBlock` methods) directly without `setTimeout`.

Please say if something needs to be clarified.

**Comment by kuuurt13** [comment]
@benj0c version `2.1.8` has been published. Can you please install and confirm that this issue was resolved?

**Comment by benj0c** [comment]
@kuuurt13 It works now.
