### ISSUE TITLE
Background color change

### ISSUE THREAD

**Issue by viveksahu1** [kuuurt13/ng-block-ui#110]
How do i change the background color of block module ?
referencing a custom template only changes the message and loading icon.

**Comment by kuuurt13** [comment]
@viveksahu1 when using a custom template it only replaces the content inside the the block and not the backdrop/wrapper. If you need to style the backdrop you will need to target `div.block-ui-wrapper` to change the color.


See example here https://stackblitz.com/edit/github-zsd8ne?file=src/styles.css

**Comment by viveksahu1** [comment]
> @viveksahu1 when using a custom template it only replaces the content inside the the block and not the backdrop/wrapper. If you need to style the backdrop you will need to target `div.block-ui-wrapper` to change the color. Let me know if that works for you.
> 
> See example here https://stackblitz.com/edit/github-zsd8ne?file=src/styles.css

Thanks a lot for the help ! .It worked

**Comment by kuuurt13** [comment]
Good to hear! Closing this issue then.
