### ISSUE TITLE
Issue request inside request

### ISSUE THREAD

**Issue by nagiramadan** [kuuurt13/ng-block-ui#116]
I set blockAllRequestsInProgress to true.
 In case of send request in subscribe of another one .(nested requests), it show block ui only in the first one only and then disappear.

**Comment by kuuurt13** [comment]
Can you please provide what version you are using and fork the below example to provide a recreation of the issue, thanks.

https://stackblitz.com/edit/github-papcjf-xqclyj

**Comment by kuuurt13** [comment]
Closing this for now. Feel free to open again with more info or an example, thanks
