### ISSUE TITLE
Angular 9.x Support

### ISSUE THREAD

**Issue by meusburger** [kuuurt13/ng-block-ui#122]
Hello guys, any prevision to work with the angular 9.x?

**Comment by teland94** [comment]
, it's not work in Angular 9

**Comment by EdwardEndovickiy** [comment]
> Hello guys, any prevision to work with the angular 9.x?

`npm install ng-block-ui@next` - This version works with ng 9

**Comment by kuuurt13** [comment]
Fixed by #113
