### ISSUE TITLE
Component calling multiple directive start/stop requests wont stop loading on second load

### ISSUE THREAD

**Issue by plevko** [kuuurt13/ng-block-ui#127]
Hello, 
I found this issue, when I am using  ng block ui directive in routed component and I have to call multiple times start/stop methods and need to navigate in/out of the component.
It behaves correctly, while I am still in the component, but it looks like that the blockCount is incorrect when I go back to component.  

Stackblitz:
https://stackblitz.com/edit/angular-7tprvv

Step to reproduce:
1. toggle
2. start blocking
3. stop blocking
4. start blocking
5. stop blocking
6. toggle
7. toggle 

-> component  with block-ui directive is loading

**Comment by kuuurt13** [comment]
Thanks for the example @plevko! I will take a look at this and see what is going on.

**Comment by cesaric** [comment]
I've been fighting this for the past couple days too on 3.0.0-beta.7.  

The **blockCount**  increments up with every blockUI.start().  You need to consecutively blockUI.stop() at least that many times to get it to stop.  blockUI.reset() will stop it absolutely but it ends up stopping any other blockUI instances on the component regardless of the name/instance passed.  

When you leave the component and come back, the BlockUi is almost always enabled/active even if you stopped it before you left the component.  I've tried wiring reset() and unsubscribe() on the onDestroy of the component but it doesn't behave as I would expect.

BlockUIService methods produce the same results.  I also tried the latest commit with the  "scoptToInstance" featire but it doesn't look like it's ready as it threw errors on initialization.

**Comment by kuuurt13** [comment]
@plevko I have made a few changes and published `3.0.0-beta.8`. I have forked your [stackblitz](https://stackblitz.com/edit/angular-cnibfn) using the newest beta and it looks like it fixes the issue that you reported. Can you give that a shot and let me know if it works for you, thanks.

**Comment by kuuurt13** [comment]
@cesaric you are correct `stop` needs to be called the same amount of times as `start`. It is designed this way so if you were to call `start` in 2 different sections or services of the app that it would `stop` once both sections/services have called `stop`. `reset` is designed to stop blocking regardless the amount of times `start` is called to get around this. If `reset` is stopping all other instances then that is a issue and I can take a look into that. 

Also, if you are having an issue with "scopeToInstance" can you open up an issue with more details? That is a new feature so if you are seeing any errors it would be great to get more info.

For now can you try installing the latest beta and see if that helps at all?

**Comment by cesaric** [comment]
@kuuurt13  thanks for the explanation on the multiple start/stops.  I completely see why that would be useful.  I just tested `3.0.0-beta.8` in my own app and the start/stop issue is completely fixed when you toggle the view/visibility of the component.  Note that the `blockCount` is always zero though (would be useful to know that count in some cases).

The `reset` still appears to be stopping all instances.  I'm also not sure if I'm implementing `scopeToInstance` properly as I can't get it working.  Here's another [stackblitz](https://stackblitz.com/edit/angular-jk6jxv) fork to demonstrate both issues.

Thanks for the quick beta update!

**Comment by plevko** [comment]
> @plevko I have made a few changes and published `3.0.0-beta.8`. I have forked your [stackblitz](https://stackblitz.com/edit/angular-cnibfn) using the newest beta and it looks like it fixes the issue that you reported. Can you give that a shot and let me know if it works for you, thanks.

wow, that was really prompt FIX. I can confirm that it works also in my case :) Thank you very much for this amazing support! 👍

**Comment by kuuurt13** [comment]
@cesaric thanks for providing the stackblitz, I really appreciate it! After looking at your code, I found out why `scopeToInstance` is not working for you. When you use that setting you need to pass the instance name `*blockUI="block1.name"` to the directive so it can be targeted correctly. 

I have also fixed the issue with `reset` clearing blocking for all instances and rolled out `3.0.0-beta.9`. Now `reset` will only target the instance it is ran on. I also added a `resetGlobal` method that will target all instances app wide to easily reset blocking for multiple instances.

Also, I forked your stackblitz and created a new [example](https://stackblitz.com/edit/ng-block-ui-issue-127-reset?file=src%2Fapp%2Fapp.component.html) with the new beta. Everything should now be working as expected. Feel free to take a look and let me know if you have any issues or questions.

**Comment by kuuurt13** [comment]
This looks to be working now so I am going to close. Feel free to open an issue if you are still running into problems.
