### ISSUE TITLE
[Question]: can we dynamically update the template?

### ISSUE THREAD

**Issue by tmtron** [kuuurt13/ng-block-ui#138]
In our use-case we have 2 very different templates for blocking the UI:  

1. during loading - we just show a loading spinner
2. when an error has occurred: we show a reload icon + message and the user can click on the template to retry

The current issue, is that we found no way to change the template once it has been assigned.  
Did we miss something?

Our workaround for now is to have only on component and pass some config parameters as explained in #95

**Comment by kuuurt13** [comment]
@tmtron this currently isn't possible because the template is only set on `ngAfterViewInit`. With that being said I think it should be possible to also update during `ngOnChanges`. Let me take a look and see if I can make this change.

**Comment by tmtron** [comment]
Okay - never mind. I think I can live with one template and config parameters.  Feel free to close this.

If you really want to add this feature it may be convenient to pass the template component in the `start()` function
