### ISSUE TITLE
Interceptor of BlockUIHttpModule runs before Angular's interceptor

### ISSUE THREAD

**Issue by suhailk4** [kuuurt13/ng-block-ui#142]
Interceptor of BlockUIhttpModule should be configured according to user and should run after Interceptor in AppModule

**Comment by suhailk4** [comment]
@kuuurt13

**Comment by kuuurt13** [comment]
@suhailk4 I'm not sure if I am following you. Can you give me more information on this? Either a code snippet or maybe go into more detail on what issue you are seeing because of this?

**Comment by suhailk4** [comment]
i believe blockUIHttp Interceptor is executing before AppModules Interceptor that we create so when request goes through App Modules interceptor and if  sometimes (so if block-ui is stopped and we are facing token expiration and want to retry request ) then 
block-ui doesn't go through block-ui httpinterceptor
