### ISSUE TITLE
Can't bind to 'blockUI' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by dennitorf** [kuuurt13/ng-block-ui#143]
Hi, I am trying to use the Block UI Directive in order to block only only div, but I am getting  this:

Can't bind to 'blockUI' since it isn't a known property of 'div'

Angular v 10

Any suggestion? 

With best regards, Denny.

**Comment by kuuurt13** [comment]
@dennitorf can you share the following details:
* What version of `ng-block-ui` you are using?
* Is this error coming in your build or in the browser console?
* Can you show me a snippet of your code and how you are using the directive?

If you can include the above, I should have a better shot at helping. Just by looking at the error, it almost seems like the `BlockUIModule` isn't being included in your imports. Can you verify that you are including it correctly by using `BlockUIModule.forRoot()`?

```ts
@NgModule({
  imports: [
    // ... Rest of imports
    BlockUIModule.forRoot() // Needs to be included
  ],
  // ... Rest of module
})
```

**Comment by dennitorf** [comment]
I did this for the app module, but, I am working in a sub module. 

It is required do this for the submodule also?

**Comment by kuuurt13** [comment]
@dennitorf thanks for the details!

Yeah, if you are using it in a sub module then you need to include it so the sub module can resolve the library. Angular modules do not inherit any imports from the module they are imported in, from what I know. So in your instance you would need to include `BlockUIModule` (don't use `forRoot`) in your sub module. See this example for more info https://stackblitz.com/edit/block-ui-issue-143?file=src/app/subModule/subModule.module.ts

Can you give that a shot and see if it works for you, thanks?

**Comment by GregoireLgt** [comment]
Hi, 

I have the same error in the browser console when i try to apply *blockUI on a div which is inside a custom angular popover component 

Any ideas ? Is it even possible to use blockUI inside a popover ?

Thx
