### ISSUE TITLE
Need to set up instance name after initialization

### ISSUE THREAD

**Issue by MatDepInfo** [kuuurt13/ng-block-ui#148]
Hello,
I need to put a dynamic name to the blockUI instance.

Example in component:
```
export class AppComponent {
  @BlockUI('hero-section') blockUI: NgBlockUI;
  dynamic_name: string;

  constructor() {
     this.dynamic_name = 'test';
    // Something like this
    this.blockUI.setXXXX(this.dynamic.name));
  }
```

Related to this template:

```
<section class="hero" *blockUI="'test'">
	<h1>NG Block UI</h1>
	<p>Block UI Implementation for Angular</p>
	<iframe src="https://ghbtns.com/github-btn.html?user=kuuurt13&repo=ng-block-ui&type=star&size=large" frameborder="0" scrolling="0"
	 width="75px" height="30px"></iframe>
</section>
```

**Comment by kuuurt13** [comment]
@MatDepInfo for this you would want to use the `BlockUIService` (see [here in the docs](https://github.com/kuuurt13/ng-block-ui#blockuiservice) for more info). I have updated your example below and also included this [stackblitz](https://stackblitz.com/edit/github-issue-148?file=src/app/app.component.ts). Let me know if this answers your question.

```ts
export class AppComponent {
  dynamicName: string = "hero-section";

  constructor(private blockUIService: BlockUIService) {
    this.dynamicName = "test";
    // Takes any blockUI name
    this.blockUIService.start(this.dynamicName);
  }
}
```

**Comment by MatDepInfo** [comment]
Thanks @kuuurt13, it is exactly what I was looking for. Sorry, I didn't see the service possibility. Have a nice day !
