### ISSUE TITLE
How to customize the loading css

### ISSUE THREAD

**Issue by seawenzhu** [kuuurt13/ng-block-ui#16]
How to customize the loading css

**Comment by kuuurt13** [comment]
@seawenzhu if you just are trying to customize the color, opacity, etc, then you can easily overwrite the css styles. I anticipated that people would want to override the styles so I made sure to use `encapsulation: ViewEncapsulation.None` on the spinner component. To override the styles you just need to either add the styles to your main app styles or add them in any separate stylesheet. I have included a working [plunker](https://embed.plnkr.co/NiFr5j?show=styles.css,preview) that uses a separate stylesheet to override the styles. Let me know if that answers your question.

**Comment by kuuurt13** [comment]
@seawenzhu I'm closing this for now, if you have any more questions on this then feel free to open it back up.

**Comment by parthdevloper** [comment]
> @seawenzhu if you just are trying to customize the color, opacity, etc, then you can easily overwrite the css styles. I anticipated that people would want to override the styles so I made sure to use `encapsulation: ViewEncapsulation.None` on the spinner component. To override the styles you just need to either add the styles to your main app styles or add them in any separate stylesheet. I have included a working [plunker](https://embed.plnkr.co/NiFr5j?show=styles.css,preview) that uses a separate stylesheet to override the styles. Let me know if that answers your question.

Your **plunker link** isn't working... Please Update

**Comment by kuuurt13** [comment]
@parthdevloper unfortunately plunker is no longer reliable but all the code is there for overriding styles in the plunker `style.css` file. That being said here is a [stackblitz](https://stackblitz.com/edit/ng-block-ui-global-styles?embed=1&file=src/styles.css) with the same code copied over.
