### ISSUE TITLE
*blockUI directive not working on IE and Edge Browser

### ISSUE THREAD

**Issue by KJcBahia** [kuuurt13/ng-block-ui#17]

**Comment by kuuurt13** [comment]
@KJcBahia I will take a look and see if I can come up with a fix.

**Comment by kuuurt13** [comment]
@KJcBahia 96a3373 should address the issue you are seeing with IE. If you could please pull down the latest version from npm and let me know if that fixes the issues you are seeing. Thanks.

**Comment by KJcBahia** [comment]
@kuuurt13 Good day! Thanks for a quick response. It is now working. Thanks :+1:

**Comment by kuuurt13** [comment]
@KJcBahia, no problem. Glad to hear it is working for you now. Closing this issue.
