### ISSUE TITLE
Build error using {{ message }} insied template component

### ISSUE THREAD

**Issue by softdays** [kuuurt13/ng-block-ui#170]
Hi
First of all I would like to thank you for the work accomplished :pray:

I'm trying to use this part of the spec: 

> When providing a Component as a template just add the {{message}} interpolation to your template and it will display your default message or the message passed to the start method.

But I got the following build error using Angular 10:

```
ERROR in libs/commons/ui-catalog/src/lib/alert-dialog/alert-dialog.component.html:58:31 - error TS2339: Property 'message' does not exist on type 'AlertDialogComponent'.

58       <div class="message">{{ message }}</div>
```

Did I miss something?

Best regards

**Comment by kuuurt13** [comment]
@softdays if I had to guess it might have to do with not declaring message in your alert dialog component. Maybe do something like below and see if that works. If that doesn't work, can you share more of your code and I can try to help debug.

 
```ts
export class AlertDialogComponent {
  message: any; // Add declaration here (use any for now to see if it fixes the issue)
}
```

**Comment by softdays** [comment]
Thanks it works as expected now 👍
