### ISSUE TITLE
Unable to start two loaders concurrently OnInit.

### ISSUE THREAD

**Issue by AjaySingh10** [kuuurt13/ng-block-ui#177]
As per the scenario I'm working on, I need to start two loaders on two different div. 
But the issue here is that the loader is only applied to the loader that was last started ignoring all the previous ones.
Is there any other workaround for the same?
Link to the issue - https://stackblitz.com/edit/github-wuybpg?file=src/app/app.component.ts

**Comment by kuuurt13** [comment]
@AjaySingh10 it looks like a timing issue with `ngOnInit`. Since you want to wait for the directives to be fully rendered you can use `ngAfterViewInit` and it should work, see this stackblitz https://stackblitz.com/edit/github-wuybpg-igwe7k?file=src/app/app.component.ts

**Comment by AjaySingh10** [comment]
That worked thank you for such a quick response.
Gratitude.
