### ISSUE TITLE
Processing legacy "View Engine" Upgrade to IVY

### ISSUE THREAD

**Issue by SwissKerim** [kuuurt13/ng-block-ui#208]
Angular 13
ng serve
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ng-block-ui [main/umd] (git+https://github.com/kuuurt13/ng-block-ui.git)
- ng-block-ui/http [fesm5/esm5] (git+https://github.com/kuuurt13/ng-block-ui.git)

My general understanding is that "View Engine" is deprecated and will eventually be removed and "Ivy" is the new next-level Angular compiler/packager. So I'm opening this issue to encourage you folks to publish an Ivy distribution of ng-block-ui

**Comment by elion** [comment]
ngcc produces the following suggestion:

```
  ngcc ... --tsconfig "tsconfig.json"
- ng-block-ui/http [fesm5/esm5] (git+https://github.com/kuuurt13/ng-block-ui.git)
- ng-block-ui/http [esm2015/esm2015] (git+https://github.com/kuuurt13/ng-block-ui.git)
...
Encourage the library authors to publish an Ivy distribution.
```

**Comment by LuisTovar0** [comment]
[ngcc has been removed in Angular 16](https://angular.io/guide/update-to-version-16#angular-compatibility-compiler-ngcc-has-been-removed). New apps can't use NgBlockUI if it's not upgraded

**Comment by kuuurt13** [comment]
Sorry for taking so long to get to this everyone. I have released a new [4.0.0-rc.1](https://www.npmjs.com/package/ng-block-ui/v/4.0.0-rc.1) version that should now fully support Ivy. Please give it a shot and let me know if anyone has any issues.

**Comment by LuisTovar0** [comment]
Thanks, the update is working fine for me. I'm consuming `NgBlockUI`, `BlockUIModule`, `BlockUIComponent`, `BlockUI` and `BlockUIDirective`

**Comment by kuuurt13** [comment]
Good to hear @LuisTovar0, thanks for testing! I have released a full release version so you should now be able to install [4.0.1](https://www.npmjs.com/package/ng-block-ui/v/4.0.1). Closing this issue but feel free to open a new one if you run into anything.
