### ISSUE TITLE
Unable to set different styles on multiple blockui objects in the same app

### ISSUE THREAD

**Issue by mttwise** [kuuurt13/ng-block-ui#25]
I was able to set styles through the global styles.css file as per the plunkr example; however, i would like to have different styles multiple block-ui items in my app.  The reason for this is that some components have different colors/backgrounds and dont look good with the same spinner style.

I tried creating a css class that sets the block-ui-wrapper background color and added it to a div with the block-ui directive, but i dont see any change.

Is it possible to do this?

**Comment by kuuurt13** [comment]
Hey @mttwise, this should be possible. You should be able to target each instance by adding a class and target that class with CSS. I'm not sure why you are having issues. If you have the directive on a component you created and you are using a global stylesheet you might want to check the components [ViewEncapsulation](https://angular.io/docs/ts/latest/api/core/index/ViewEncapsulation-enum.html) it could be preventing the global styles from being applied. If you can create a plunker with an example I might be able to help out a little more.

Another possible solution if you don't want to manually add classes is to use the block-ui name that is added to every instance. When you pass a name to the blockUI directive/component `*blockUI="'example'"` that name is added as a class to the `block-ui-wrapper` div. You can then use that to style instances individually. I created this [plunker](https://embed.plnkr.co/exJ9zTwMrk5l1aVQRqbU?show=styles.css,preview&autoCloseSidebar) as an example.

Hope this helps, let me know if it solves your issue.

**Comment by mttwise** [comment]
@kuuurt13, Thanks so much for the advice.  The issue ended up being that i needed to set my ViewEncapsulation to None.  The plunkr helped out a lot to see how to properly set the css.

Its working perfectly now!

**Comment by kuuurt13** [comment]
@mttwise, no problem. Good to hear, glad you figured it out :+1:
