### ISSUE TITLE
Using custom template with blockui directive

### ISSUE THREAD

**Issue by hnguyenec** [kuuurt13/ng-block-ui#27]
In a container template, i used blockui directive to a specific div. 
In another service, I used blockui service to trigger start even manually

However i dont know how to use custom template along with blockui directive, so that when Start event is triggered, it will use custom template instead of the default one

**Comment by kuuurt13** [comment]
Hey @hnguyenec, you previously couldn't pass a custom template to directives (only to the `block-ui` component) but I just implemented this feature so you should be able to use a custom template. If you get the newest version (`0.8.0`/`1.0.0-beta.11`) it will allow custom templates to be passed to the directive.

For structural directives extra inputs are passed in a different way. You will need to pass the template as a key/value pair like so `<div *blockUI="'block-name'; template: templateCmp"></div>`. I created this [plunker](https://embed.plnkr.co/USHJ3X?show=app.compontent.html,preview&autoCloseSidebar) as an example so please refer to that for more info. Let me know if you have any questions.

**Comment by hnguyenec** [comment]
it works great.
Thanks for your updates and prompt response
