### ISSUE TITLE
BlockUI karma test failure

### ISSUE THREAD

**Issue by marwanhyouness** [kuuurt13/ng-block-ui#28]
The BlockUI is failing the test cases it's used in as it can't be instantiated
```TS
TypeError: undefined is not an object (evaluating 'this.blockUISubscription.unsubscribe') in tests/main.js (line 67818)
	onUnsubscribe@webpack:///~/ng-block-ui/dist/lib/components/block-ui-content/block-ui-content.component.js:93:0 <- tests/main.js:67818:37
	ngOnDestroy@webpack:///~/ng-block-ui/dist/lib/components/block-ui-content/block-ui-content.component.js:97:0 <- tests/main.js:67822:27
	ngOnDestroy
	destroyInternal
	destroy@webpack:///~/@angular/core/src/linker/view.js:203:0 <- tests/main.js:121767:29
	destroy@webpack:///~/@angular/core/src/linker/view.js:606:0 <- tests/main.js:122170:42
	destroyInternal
	destroy@webpack:///~/@angular/core/src/linker/view.js:203:0 <- tests/main.js:121767:29
	destroy@webpack:///~/@angular/core/src/linker/view.js:606:0 <- tests/main.js:122170:42
	destroyInternal
	destroy@webpack:///~/@angular/core/src/linker/view.js:203:0 <- tests/main.js:121767:29
	destroy@webpack:///~/@angular/core/src/linker/view.js:606:0 <- tests/main.js:122170:42
	detachAndDestroy@webpack:///~/@angular/core/src/linker/view.js:187:0 <- tests/main.js:121751:21
	destroy@webpack:///~/@angular/core/src/linker/component_factory.js:147:51 <- tests/main.js:62750:86
	destroy@webpack:///~/@angular/core/bundles/core-testing.umd.js:263:0 <- tests/main.js:9202:42
	webpack:///~/@angular/core/bundles/core-testing.umd.js:728:61 <- tests/main.js:9667:85
	forEach@[native code]
	resetTestingModule@webpack:///~/@angular/core/bundles/core-testing.umd.js:728:0 <- tests/main.js:9667:41
	resetTestingModule@webpack:///~/@angular/core/bundles/core-testing.umd.js:636:0 <- tests/main.js:9575:44
	webpack:///~/@angular/core/bundles/core-testing.umd.js:967:0 <- tests/main.js:9906:39
	invoke@webpack:///~/zone.js/dist/zone.js:242:0 <- tests/main.js:108259:31
	onInvoke@webpack:///~/zone.js/dist/proxy.js:79:0 <- tests/main.js:107913:45
	invoke@webpack:///~/zone.js/dist/zone.js:241:0 <- tests/main.js:108258:40
	run@webpack:///~/zone.js/dist/zone.js:113:0 <- tests/main.js:108130:49
	webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- tests/main.js:107628:37
	execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- tests/main.js:107658:46
	execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- tests/main.js:107658:46
	invokeTask@webpack:///~/zone.js/dist/zone.js:275:0 <- tests/main.js:108292:40
	runTask@webpack:///~/zone.js/dist/zone.js:151:0 <- tests/main.js:108168:57
	drainMicroTaskQueue@webpack:///~/zone.js/dist/zone.js:433:0 <- tests/main.js:108450:42
	invoke@webpack:///~/zone.js/dist/zone.js:349:0 <- tests/main.js:108366:44
	webpack:///~/zone.js/dist/zone.js:1376:0 <- tests/main.js:109393:30
```

**Comment by kuuurt13** [comment]
@marwanhyouness not sure what is going on here. Currently all tests are passing for both currently released versions of the library on the [build server](https://travis-ci.org/kuuurt13/ng-block-ui/builds). Can you maybe give me more info into what you are trying to test and let me know what version you are using by running `npm list ng-block-ui`. Thanks.

**Comment by marwanhyouness** [comment]
@kuuurt13 
Thanks for the reply. I'm using v 0.8.0. My test just checking if the component was initiated properly.
here is the code

import { TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { ReactiveFormsModule } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import {
    ApiService,
    ApplicationService,
    MessagesParser
} from '../../../shared/services';
import {
    ToastrServiceMock ,
    ApiServiceMock,
    ApplicationServiceMock,
    MessagesParserMock
} from '../../../util/mocks';
import { RegisterComponent } from './register.component';
//import { BlockUIModule , NgBlockUI } from 'ng-block-ui';


describe("Register Component" , () => {
    let fixture;
    let component: RegisterComponent;
    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [ RouterTestingModule , ReactiveFormsModule ],
            declarations: [ RegisterComponent ],
            providers: [
                { provide: ToastrService , useClass: ToastrServiceMock },
                { provide: ApiService , useClass: ApiServiceMock },
                { provide: ApplicationService , useClass: ApplicationServiceMock },
                { provide: MessagesParser , useClass: MessagesParserMock }
            ]
        });

        fixture = TestBed.createComponent(RegisterComponent);
        component = fixture.componentInstance;
    });

    it('should be defined' , () => {
        expect(component).toBeDefined();
    })
})

i removed the block-ui component and the test passed

**Comment by kuuurt13** [comment]
@marwanhyouness thanks for more details. I take it that you have either the block-ui component or directive in the template of your `RegisterComponent`? If so then I think you need to uncomment `import { BlockUIModule , NgBlockUI } from 'ng-block-ui';` Then you need to add the `BlockUIModule` to your `configureTestingModule` imports. I think that should fix your issue. Let me know if that works.

```ts
// ...
import { BlockUIModule , NgBlockUI } from 'ng-block-ui';

describe("Register Component" , () => {
    let fixture;
    let component: RegisterComponent;
    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [ 
              RouterTestingModule, 
              ReactiveFormsModule, 
              BlockUIModule // Add BlockUIModule 
            ],
            declarations: [ RegisterComponent ],
            // ...
        });
// ...
})

```

**Comment by kuuurt13** [comment]
@marwanhyouness  any update on this?

**Comment by kuuurt13** [comment]
Closing, for now. Please reopen if you are still having issues.
