### ISSUE TITLE
Stop method does not seem to work

### ISSUE THREAD

**Issue by jamesfe** [kuuurt13/ng-block-ui#30]
I am noticing that whatever the first call to my instance of blockUI works but subsequent calls do not.  This means I can start blocking but cannot stop (obviously a problem).  I feel like this might be user error but am unsure - my project uses angular 4.3.2, ng-block-ui beta 12 and material 2.0.0-beta8 among other things.

Is there more information I can provide or have you run into this problem elsewhere?  If so then I can update the docs with any solutions you might suggest.

**Comment by kuuurt13** [comment]
@jamesfe, hmm not sure what is going on. I have implemented a delay setting to the library for starting/stopping so maybe it could be a bug there. All my tests are passing but there still could be a bug. 

First thing you can do is to roll back the library before those changes for the time being and see if it fixes your issue. Can you run `npm install ng-block-ui@1.0.0-beta.11` and then test to see if it works. 

If it still doesn't work then it might just be user error or something else. If so, can you either give me an example of how you are using it or even better create a plunker (you can fork this [plunker](https://plnkr.co/edit/ZVDRrq)).

**Comment by jamesfe** [comment]
Thanks for such a quick response - and for this library too!  It's tough maintaining open source code :)

I think the error might be on my side but I'm not sure.  I can't get a plunker to break, but I also do not know how to specify all the library versions on the plunker.  Here is one that works but I can't set the npm package versions on: https://plnkr.co/edit/P8JSeOlGwcsqRk4DEHhJ

Below are my current dependencies.  I rolled back to beta11 and am still experiencing the same thing.  Maybe you will see something there that you recognize as a problem.

I can debug into the code and the BlockUI object is still there, some function is executed but I'm not sure what's going wrong - it is entirely possible this is not your library but some strange TypeScript interaction or even a problem with the way our templates are written.  I have switched the `<block-ui>` to wrap all sorts of other elements.

Notably if I call `blockUI.start("slkdfj")` with different text or `blockUI.update('other text')`, nothing happens.  It's like after the first call to that object, it is locked down and will not act on future function calls.  Maybe the DOM is at some point "disconnected" from the object?

```
  "dependencies": {
    "@angular/animations": "^4.3.2",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.3.2",
    "@angular/compiler": "^4.3.2",
    "@angular/core": "^4.3.2",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.3.2",
    "@angular/http": "^4.3.2",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.3.2",
    "@angular/platform-browser-dynamic": "^4.3.2",
    "@angular/router": "^4.3.2",
    "@material/button": "^0.3.10",
    "@material/toolbar": "^0.4.3",
    "angular2-moment": "1.3.3",
    "core-js": "2.4.1",
    "moment": "2.18.1",
    "ng-block-ui": "^1.0.0-beta.11",
    "rxjs": "5.4.0",
    "zone.js": "^0.8.10"
  }
```

**Comment by jamesfe** [comment]
Actually I am finding that in debugging there are some variables which are set to undefined at the time when the `update` call is sent (after the `start` call).  

Specifically this: https://github.com/kuuurt13/ng-block-ui/blob/ab1a1eb1d38046523d5aab45f31549f84ecb3016/lib/components/block-ui-content/block-ui-content.component.ts#L69 is set only conditionally but the template cannot be updated if it has not been set already: https://github.com/kuuurt13/ng-block-ui/blob/ab1a1eb1d38046523d5aab45f31549f84ecb3016/lib/components/block-ui-content/block-ui-content.component.ts#L147

Maybe somewhere between angular/material2/etc. then `ngAfterViewInit` is not being fired?  Or `templateCmp` is not being set?

**Comment by kuuurt13** [comment]
@jamesfe I got some time to look at your plunker. I could be wrong but it looks like you are just trying to toggle the start and stop from a child component, is that correct? If so I think you are over complicating it a bit in this example which makes me think that the issue in your local repo might have something to do with your approach. 

Any variable declared with the `@BlockUI()` decorator always has reference to the main block no matter where it is declared. So if you want to start and stop from a child component there would be no need to create a service to communicate up to the parent. You would just declare `@BlockUI() blockUI` in your child component and call start/stop. I forked you plunker to show you what I mean. Take a look and let me know https://plnkr.co/edit/3LWDCW1OBcD7SwSrBABV?p=preview

**Comment by jamesfe** [comment]
@kuuurt13 Well I discovered this little gem sitting in my (our) code: https://plnkr.co/edit/7lumJNrwYUbpMM1D70jU - it looks like I have some work to do on my side but I believe if I remove this, it'll probably fix my "issue".  Thanks for your time, hopefully this is of some use to you.

**Comment by kuuurt13** [comment]
@jamesfe oh wow so it looks like it has to do with `changeDetection: ChangeDetectionStrategy.OnPush` being on the parent component and using a timeout. If the stop is called in the app component it works [though](https://plnkr.co/edit/ooSLD1wyvVmEY1NiOREh?p=preview) 😕 . I would have to debug more to see what angular is doing behind the scenes here. I quickly googled it and found this [article](http://blog.angular-university.io/onpush-change-detection-how-it-works/) and the first paragraph is pretty spot on 😆

**Comment by jamesfe** [comment]
Yes, it was quite the "punch myself in the face moment" - I will get further into this next week when I am back at my other computer.

**Comment by kuuurt13** [comment]
@jamesfe I just put in a change for #33 and It looks like it will fix the issue you were seeing when using `changeDetection: ChangeDetectionStrategy.OnPush` . I pushed a new version and tested the [plunker]( https://plnkr.co/edit/7lumJNrwYUbpMM1D70jU) you used to highlight the issue earlier and it seems to fix the issue. Take a look and let me know.

**Comment by jamesfe** [comment]
Thanks!  I think this will work out.  Our team is using a method called "FRP" so we are avoiding emitting events and use Observables all over.  I'm new to it (and Angular, even JS to a degree) so I think it was probably more error on my side than anything.  Either way, I really appreciate all the help you've provided!!

**Comment by kuuurt13** [comment]
Okay, no problem. I'm going to close this issue then.
