### ISSUE TITLE
beta.13 after npm install module contain just metadata.json files.

### ISSUE THREAD

**Issue by Oleg1969** [kuuurt13/ng-block-ui#31]
After installing latest @next version (beta 13) "dist" folder contains only metadata.json files.
Resulting to error:  Cannot find module 'ng-block-ui'.

**Comment by ddivita** [comment]
Just noticed this myself

**Comment by kuuurt13** [comment]
@Oleg1969 @ddivita it looks like it was a bad npm build ☹️ . Really sorry for that. Please install with the `@next` tag to get beta 14 and it should be fixed. Sorry for any inconvenience.

**Comment by Oleg1969** [comment]
it works now. thanks

**Comment by ddivita** [comment]
Confirmed. Thanks

**Comment by kuuurt13** [comment]
Closing since this looks to be good now.
