### ISSUE TITLE
Change Detection OnPush

### ISSUE THREAD

**Issue by nerumo** [kuuurt13/ng-block-ui#33]
the BlockUIContent component should call `changeDetector.markForCheck()` on `onDispatchedEvent`. 

If you have a component tree that is completely `OnPush`, then you don't always get the update

**Comment by kuuurt13** [comment]
@nerumo this is great insight, I appreciate it. This looks like it would fix the issue we were seeing with #30. I will look into this weekend and add in the changes if I can.

**Comment by kuuurt13** [comment]
@nerumo so I tried adding `changeDetector.markForCheck()` but it still was not picking up some of the changes so I had to call `changeDetector.detectChanges()` whenever a block event was dispatched and it worked. I tested it with the specific issues we were seeing (see issue #30) and it fixed them. Could you please install the latest version of the library and see if it fixes the issues you were seeing with `onPush` if you had any? Thanks

**Comment by nerumo** [comment]
thanks, I can confirm that it works now

**Comment by kuuurt13** [comment]
Good, to hear 👍
