### ISSUE TITLE
A button to custom template

### ISSUE THREAD

**Issue by epaitz** [kuuurt13/ng-block-ui#35]
Is it possible to add a button to a custom block template? I have been following the example code and I was able to get a custom template created with a cancel button inside the block-template.component.html.

`<button type="button" (click)="cancel()"></button>`

block-template.component.ts.

`cancel() { console.log('cancel()'); }`

Now I am getting a tslint error on the following line.

`blockTemplate: BlockTemplateComponent = BlockTemplateComponent;`

> TS2322: Type 'typeof BlockTemplateComponent' is not assignable to type 'BlockTemplateComponent'. Property 'cancel' is missing in type 'typeof BlockTemplateComponent'.

The odd thing is that it will run even with the tslint error so I assume I can just suppress this error. I guess the bigger question is how can I get the cancel click event to propagate to the component using the blockUI so that I can cancel the current work?

I would think an easier way to modify the template would be not not have to create a new component but to define an in-line template in the component's HTML that is using the blockUI but I have not been successful getting that to work. 

Any suggestions would be greatly appreciated.

**Comment by kuuurt13** [comment]
@epaitz it is tough to solve your issue 100% without having a more code to look at. With that being said I created a [plunker](https://embed.plnkr.co/rZXnS0mMCRc4rGX3w9VV/?show=block-template.component,preview&autoCloseSidebar) that has a custom template with a button that stops the blocking when clicked. Take a look at that and let me know if that helps you at all.

**Comment by epaitz** [comment]
Thanks very much for the fast reply! I am looking at the plunker you posted now. I think the last piece is that the calling component, app component in this case, needs to be made aware the user has clicked the stop button so that it can stop the async work. In my scenario I have a component, with an injected service, that has started some async work using that service and if the user clicks stop/cancel I need to cancel the work that the service is performing.

**Comment by kuuurt13** [comment]
@epaitz I reworked the [plunker](https://plnkr.co/edit/NeWGai1h0tGZUKNg5kRB?p=preview) and added a service that is canceled when you click the cancel button. Let me know if this works for you.

**Comment by nrehm** [comment]
Have to hijack this issue a bit sorry.
Is it possible to add custom template with button to a section?

**Comment by kuuurt13** [comment]
@nrehm yes, you would just update the plunker above to use the directive instead of the component. Angular has a weird syntax for passing additional parameters to structural directives. Here is an updated version of the [plunker](https://plnkr.co/edit/GxdsOJBmfnMeDXOxuITv?p=preview) above. Also you can see this issue for more info https://github.com/kuuurt13/ng-block-ui/issues/36

**Comment by kuuurt13** [comment]
@nrehm @epaitz can I close this issue or are any of you still having issues?

**Comment by epaitz** [comment]
I accomplished what I needed a different way. Thanks for all the information. I am ok if you close it but I cant speak for @nrehm. Thanks.

**Comment by kuuurt13** [comment]
Thanks @epaitz I'm closing then
