### ISSUE TITLE
How to specify a custom template on a directive?

### ISSUE THREAD

**Issue by tobecwb** [kuuurt13/ng-block-ui#36]
So, like the title says, how to specify a custom template if I'm using a directive to block only certains elements?

I'm using the ng-block-ui to block my form if on ngInit() a error occur (when I ask with REST for some info, and this server is not available).

**Comment by kuuurt13** [comment]
@tobecwb Angular has a weird syntax for how to pass multiple attributes to structural directives. Here is a [plunker](https://embed.plnkr.co/USHJ3X?show=app.compontent.html,preview&autoCloseSidebar) that shows you how you can pass a custom template.

**Comment by tobecwb** [comment]
Tks! worked good! never used directives in this way!
