### ISSUE TITLE
There seems to be no way of creating a custom template to a directive

### ISSUE THREAD

**Issue by gamesgil** [kuuurt13/ng-block-ui#37]

**Comment by kuuurt13** [comment]
@gamesgil please see https://github.com/kuuurt13/ng-block-ui/issues/36 this should help you out

**Comment by gamesgil** [comment]
Thank you very much for the quick answer! Indeed it does. However I didn't find a way to customize the blocking background without fiddling with the sources. Is there a way?

**Comment by gamesgil** [comment]
Thank you very much for the quick answer! It worked.

**Comment by kuuurt13** [comment]
@gamesgil, good to hear! Closing this issue.
