### ISSUE TITLE
is it work for automatic blocking for http request ? 

### ISSUE THREAD

**Issue by Assdi** [kuuurt13/ng-block-ui#38]
just like this [https://github.com/McNull/angular-block-ui](url)

**Comment by kuuurt13** [comment]
Currently, this hasn't been implemented but it is something I can explore as a feature for a future release.

**Comment by eduardoleopoldino** [comment]
Is there a way to check if a instance is active? I have some keyboard shortcuts that I need to check if there's another action going. In this case, i want to check if BlockUI is active before triggering the action. 

On your code, you have a *this.active* property inside *BlockUIContentComponent* that i believe would help. But you need to expose this property to @BlockUI decorator.. Or is there any other way?

**Comment by kuuurt13** [comment]
@eduardoleopoldino currently this isn't possible. This seems like something that should be added as a feature. I moved this over to issue #40 since this ticket is more about automatic http request blocking.

**Comment by RobPierce** [comment]
It would also be really neat, if implementing automatic http request blocking, to allow a request filter to turn off filtering for specific paths, as angular-block-ui does.

**Comment by kuuurt13** [comment]
@RobPierce I agree I will make sure to include this 👍

**Comment by kuuurt13** [comment]
With the new `1.0.0` release you can now automatically block http requests, see the [HTTP Module](https://github.com/kuuurt13/ng-block-ui/blob/master/docs/http-module.md#automatically-block-http-requests)

**Comment by Assdi** [comment]
thanks @kuuurt13  I will check it :+1:
