### ISSUE TITLE
Prevent browser navigation for all http request

### ISSUE THREAD

**Issue by kesdeband** [kuuurt13/ng-block-ui#39]
Sorry, check out this link: https://github.com/McNull/angular-block-ui#blockbrowsernavigation

**Comment by kuuurt13** [comment]
Can you give more details on this and why you think this is needed?

**Comment by kesdeband** [comment]
Check out this example: https://github.com/McNull/angular-block-ui#blockbrowsernavigation

**Comment by kuuurt13** [comment]
Now in `1.0.0` you can prevent navigation while block see the [Router Module](https://github.com/kuuurt13/ng-block-ui/blob/master/docs/router-module.md#prevent-navigation-during-active-block-ui)
