### ISSUE TITLE
Binding to element with a custom template doesn't work.

### ISSUE THREAD

**Issue by EduardsE** [kuuurt13/ng-block-ui#42]
Basically I tried to merge **BlockUI Directive**  and **BlockUI Custom Template**, but I can't get it to work. 

Here's the plnkr.
https://plnkr.co/edit/54n6SP?p=preview

**Comment by kuuurt13** [comment]
Please see #36. It has a link to a plunker example that will help you out. I am making a few changes to the library for a 1.0.0 release and it will allow a custom template to be configured on the BlockUIModule. That way you won't need to explicitly pass a template to the directive and it will just inherit it from the module.

**Comment by EduardsE** [comment]
Oh, thx. Sorry, I forgot to check the old issues, only the open/current ones.

**Comment by kuuurt13** [comment]
No problem, glad I could help. Going to close this.
