### ISSUE TITLE
add option to track blocking/unblocking ui

### ISSUE THREAD

**Issue by kopach** [kuuurt13/ng-block-ui#43]
It would be great to have an option to "unblock" only if `stop()` function was called the same amount as `start()`

Example:

Suppose I have 3 async functions:

- loadUsers
- deleteUserFromList

Each of this function may be called independently, so each of it runs `blockUI.start()` on the beginning and `blockUI.stop()` on finish. Everything is fine, unless I want to make some of those operations in parallel.

For example:

- deleteUserFromList()
   - **blockUI.start()**
   - onSuccess
      - loadUsers()
        - **blockUI.start()**
        - onComplete
          - **bockUI.stop()**
      - some other operation, e.g. refreshUserTable()
    - onComplete
      - **bockUI.stop()**

So, as you may see, blockUI will stop showing once `loadUsers` finish but it should stop only after all the operations complete.

**Comment by kuuurt13** [comment]
@kopach I can understand your problem here and I thank you for the example, it made it really easy to understand your issue. I can see how this can be a pain point but I'm not sure if your purposed solution should be included within this library. The reason being is that this could just be addressed by how you structure your code. What I would do is just use the RxJS `forkJoin` operator (it is very similar to `Promise.all` or the angularjs equivalent `$q.all`) to wait for all the requests and then stop blocking once they are all resolved. See my example below and this [plunker](https://plnkr.co/edit/t9sk8g?p=preview) for a more elaborate example.

```ts
this.blockUI.start();
  
forkJoin(
  this.serviceOne(),
  this.serviceTwo()
).subscribe(() => this.blockUI.stop());
```

**Comment by kopach** [comment]
@kuuurt13, thanks for your explanation. I can agree that in most of the cases such a solution will work, but not for all the cases. Let me show you on your  example:

```
this.blockUI.start();
  forkJoin(
  this.serviceOne(), // async call, uses internally blockUI
  this.serviceTwo() // also async call and also uses internally blockUI
).subscribe(() => this.blockUI.stop());
```

So, it may be the situation, when `serviceOne` finished and stopped block UI, while `serviceTwo` is till running and expecting blockUI to be visible.

I understand, you may say - don't use blockUI inside `serviceOne` and `serviceTwo`. but - it's more code and complicates all the functionality. Say, I have `serviceOne` which uses blockUI internally. I want to show blockUI always while `serviceOne` is running. But, on some point I may want to run this in parallel with some other async function and `forkJoin` then. In this case, to make sure `blockUi` will work as I expect - I would need to extract it from `serviceOne` and have 2 functions of `serviceOne` (function itself and some wrapper with blockUI):

1) for independent call with blockUI,
2) for parallel call without blockUI to be executed within some `forkJoin` call

So, solution I like more - create local wrapper of blockUI which will have some start/stop stack. But, the beset would be if lib itself could handle this (could be with some flag)

What do you think?

**Comment by kuuurt13** [comment]
@kopach, I see where you are coming from on this. If this is a feature that a lot of users would find useful then I can look into implementing it. I'm currently working on a bunch of tasks for a `1.0.0` release of this library that includes a bunch of long overdue changes. Once I roll that out I can start looking into this more thoroughly.
