### ISSUE TITLE
Remove warning please

### ISSUE THREAD

**Issue by yesparthasarathy** [kuuurt13/ng-block-ui#47]
Template parse warnings:
```
The <template> element is deprecated. Use <ng-template> instead ("
    </div>
  </div>
  [WARNING ->]<template *ngIf="templateCmp" #templateOutlet></template>
</div>
")
```

**Comment by kuuurt13** [comment]
@yesparthasarathy can you give me more info on this. Like maybe an example of how to reproduce the warning?

**Comment by kuuurt13** [comment]
@yesparthasarathy looks like you did include an example but the markdown was formatted weird and it wasn't visible. I updated your comment and added a code block to fix it. 

As for that warning, I take it you are using Angular >= 4.x. If so you need to install the library with the `next` flag `npm install ng-block-ui@next --save`.  Please see the [installation](https://github.com/kuuurt13/ng-block-ui#installation) section in the docs for more info. Let me know if that fixes the warning.

**Comment by kuuurt13** [comment]
@yesparthasarathy did that fix it for you?

**Comment by yesparthasarathy** [comment]
yes it got fixed..
