### ISSUE TITLE
Append custom template to body

### ISSUE THREAD

**Issue by vodess** [kuuurt13/ng-block-ui#48]
Hi,

Can you please implement a possibility to append custom blockUI template to body with correct position (above element with *blockUI directive)?

Suggestion of use:

`<div *blockUI="'myElement'; template: blockTemplate" appendTo="body">...</div>`

**Comment by kuuurt13** [comment]
I think this would be very big undertaking to accomplish. Currently, when you use the directive the overlay is added within the element so it can use css to position itself within the element in a relatively simple and uncostly manner. Adding it to the body would require extensive javascript and DOM manipulation to position the overlay. The overlay would have to calculate the position and size for every blocked element which could be pretty costly as opposed to just using CSS.

Can I ask why you would want the blockUI overlay to be added to the body?

**Comment by vodess** [comment]
I want it because when I have some other overlays, such as popovers or tooltips bound to body with absolute positions, they appear above blockUI template. In my opinion blockUI template is an element for which it has to be guaranteed that it's the topmost element in z-order.

**Comment by kuuurt13** [comment]
I understand where you are coming from but couldn't you just manipulate the z-index CSS to make the blockUI overlay the highest so then it overlays all the elements in the body? I was messing around with this locally and it seemed to work.

So something like
```css
.block-ui-wrapper.block-ui-wrapper--element {
  z-index: <make higher than other body elements>
}
```

**Comment by vodess** [comment]
I could not because my block UI template is bound to some lower element (e.g. <form>), and the popovers are direct children of body. That's why they're always above blocked form.

**Comment by kuuurt13** [comment]
I see, well if you want to take a shot at it PR are always welcome 👍
