### ISSUE TITLE
Angular universal - SSR issue

### ISSUE THREAD

**Issue by davidsekar** [kuuurt13/ng-block-ui#49]
Thanks for your efforts in bringing up this wonderful Block UI module.

Currently, following line throws error during Server Side Rendering using Angular universal
https://github.com/kuuurt13/ng-block-ui/blob/1bb0140178edd699fcaa976a720677a215e44db5/lib/directives/block-ui.directive.ts#L49

Would it be possible for you to may be use Renderer or Renderer2 and add the class name as following
`this.renderer.addClass(parentElement, 'block-ui__element');`

**Comment by kuuurt13** [comment]
Hey @davidsekar, I updated the directive to use `Renderer2` and published the changes to npm in version `1.0.0-beta.17`. Please test and let me know if that fixes the issues you were seeing with Angular Universal.

**Comment by davidsekar** [comment]
@kuuurt13 With the new beta release, this issue doesn't happen any more. 

Thanks for a quick issue fix and beta release. 👍

**Comment by kuuurt13** [comment]
No problem. Closing the issue then 👍
