### ISSUE TITLE
'message' is private and only accessible within class 'BlockUIContentComponent'

### ISSUE THREAD

**Issue by Swellenator** [kuuurt13/ng-block-ui#51]
With latest Angular 5.2, cli 1.6.5, ng-block-ui@next, I get the error 

    ERROR in node_modules\ng-block-ui\dist\lib\components\block-ui-content\block-ui-
    content.component.d.ts.BlockUIContentComponent.html(5,60): : Property 'message' is private and only 
    accessible within class 'BlockUIContentComponent'.
    node_modules\ng-block-ui\dist\lib\components\block-ui-content\block-ui-
    content.component.d.ts.BlockUIContentComponent.html(5,10): : Property 'message' is private and only 
    accessible within
    class 'BlockUIContentComponent'.

I am executing ng build --prod. I have also enabled "fullTemplateTypeCheck" in the angular compiler options in the tsconfig.json.

If I go into `block-ui-content.component.d.ts` and make `message` public it all works fine.

**Comment by kuuurt13** [comment]
@Swellenator I will take a look at this tonight. Should be able to roll a new version with this change.

**Comment by kuuurt13** [comment]
@Swellenator please update to `1.0.0-beta.18` and see if that fixes your issue. Thanks!

**Comment by Swellenator** [comment]
Yep cheers works good, thanks for the quick response!
