### ISSUE TITLE
error during cleanup of component with Karma

### ISSUE THREAD

**Issue by shalinparmar** [kuuurt13/ng-block-ui#52]
I am using BlockUI @next with Angular 5+. It works fine in app but the unit testing fails with error:
'Cannot read property 'unsubscribe' of undefined at BlockUIContentComponent.webpackJsonp'. The reason being that Karma doesn't instantiate the BlockUI object (i.e. no call is made to ngOnInit) but it calls ngOnDestroy() and fails there because the subscription was never set.

Please let me know how to fix this?

**Comment by kuuurt13** [comment]
@shalinparmar I haven't seen this in any of my karma tests but it looks like something I would need to put a fix in for. I can add an extra check [on this line](https://github.com/kuuurt13/ng-block-ui/blob/master/lib/components/block-ui-content/block-ui-content.component.ts#L154) to make sure it is defined.

**Comment by kuuurt13** [comment]
@shalinparmar I added the fix for this and published a new version to npm. Update to ` 1.0.0-beta.19` to get the fix. Let me know if that fixes your issue.

**Comment by kuuurt13** [comment]
@shalinparmar closing since this should be fixed. If you continue to see the issue I will open this back up. Thanks
