### ISSUE TITLE
Error with AOT compiler and angular cli

### ISSUE THREAD

**Issue by thiagov** [kuuurt13/ng-block-ui#53]
Hello, I recently updated ng-block-ui to  verion 1.0.0-rc.1 (I am using Angular 5). I updated the module import, like described [here](https://github.com/kuuurt13/ng-block-ui/blob/1.0.0-release/docs/migration-1.0.0.md).

When I try to compile the application with angular cli, using `ng serve --aot`, I get the following error:

``
  Function calls are not supported in decorators but 'BlockUIModule' was called.
``

Is there a workaround?

**Comment by kuuurt13** [comment]
@thiagov thanks for testing out the RC! I will take look into this.

**Comment by kuuurt13** [comment]
Hey @thiagov looks like I needed to make some changes to how settings are injected. I tested locally with a new project created with angular cli and running `ng serve --aot`. 

Install the latest rc (`1.0.0-rc.2`) and you should no longer see the error. Let me know if that works for you.

**Comment by thiagov** [comment]
Thanks @kuuurt13! I installed the latest rc and it solved the problem.

**Comment by symlynk** [comment]
Since upgrading Angular, I am seeing this error when attempting to build with: ng build --prod

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'BlockUIHttpModule' was called.

BlockUIHttpModule.forRoot() is causing the error, but only when building as production. Using 2.1.1 of ng-block.ui

Angular CLI: 1.6.6
Node: 10.15.1
OS: win32 x64
Angular: 5.2.2

**Comment by kuuurt13** [comment]
@symlynk the issue is that `2.x.x` requires Angular 6 or above and you are using `5.2.2`. Please see https://github.com/kuuurt13/ng-block-ui/blob/master/docs/migration-2.0.0.md

**Comment by nuno-tiago-reis** [comment]
Hello, this seems to happen with the 3.0.0-beta.1.
I'm using Angular 8.

**Comment by kuuurt13** [comment]
@nuno-tiago-reis I will look into this tonight

**Comment by kuuurt13** [comment]
@nuno-tiago-reis I think I have fixed the issue, can you please upgrade to the latest version (npm i -S ng-block-ui@next) and see if that fixes your issue?

**Comment by nuno-tiago-reis** [comment]
It doesn't happen anymore, but block UI seems to stick around forever.
I've downgraded to 2.1.8 right now since I don't have the time to investigate if there's something I did wrong.

**Comment by kuuurt13** [comment]
Okay, well if you do upgrade again and have issues feel free to open another issue with the details.
