### ISSUE TITLE
No provider for BlockUIInstanceService

### ISSUE THREAD

**Issue by emranashraf** [kuuurt13/ng-block-ui#54]
I'm trying to use ng-block-ui with Angular 5 in a Angular CLI project.

in my app.module.ts I imported the component as following
import { BlockUIModule } from 'ng-block-ui';

then added in import block
imports: [
  BlockUIModule 
]

but i'm getting error  "No provider for BlockUIInstanceService!"

Any idea what I'm doing wrong. Do I have to do some extra steps in an Angular CLI project as I can't find any online example as all examples were implemented using SystemJs.

Thanks
Imran

**Comment by kuuurt13** [comment]
@emranashraf what version of `ng-block-ui` are you using? Can you run `npm list ng-block-ui` so I can be sure what version you are using.

If you explicitly installed `1.0.0-rc.x` then you can find the updated docs for that on the [1.0.0-release branch docs](https://github.com/kuuurt13/ng-block-ui/tree/1.0.0-release#installation) since it has yet to be merged into master.

**Comment by emranashraf** [comment]
I ran this command "npm list ng-block-ui" it's showing version ng-block-ui@1.0.0-rc.2
But I installed it with the following command
npm install ng-block-ui@next

and in package.json 1.0.0-beta.19 version is being shown

Thanks for your quick reply

Regards,
Imran

**Comment by emranashraf** [comment]
By using BlockUIModule.forRoot() in import block fixed my issue.

Thanks
Imran

**Comment by kuuurt13** [comment]
Good to hear, closing this issue

**Comment by cybercussion** [comment]
I was getting a lot of errors related to it not finding BlockUIInstanceService, I had to do effectively:

```TypeScript
import { BlockUIModule, BlockUIService, NgBlockUI } from 'ng-block-ui';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'; // dropdown

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        BlockUIModule.forRoot(),
        BrowserAnimationsModule
      ],
      providers: [
        BlockUIModule
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));
```

Case it helps anyone.
