### ISSUE TITLE
BlockUIHttpModule not working

### ISSUE THREAD

**Issue by bigshiny90** [kuuurt13/ng-block-ui#57]
import { BlockUIHttpModule } from 'ng-block-ui/http';

cannot find module.   i properly npm installed ng-block-ui, seems everything is setup properly.

am i missing something?

**Comment by kuuurt13** [comment]
@bigshiny90 that seems right. It could be a bundling issue with npm that I didn't run into when testing locally. I will take a look.

**Comment by bigshiny90** [comment]
nice, thx man ;)  Looks like a great library, looking forward to trying it!

**Comment by kuuurt13** [comment]
@bigshiny90 thanks, I appreciate it. It definitely is an issue with how I am packaging it with npm. It's not ideal but a work around for now would be to import as so:
```
import { BlockUIHttpModule } from 'ng-block-ui/dist/http';
```

I will continue to look into this and see if I can fix the issue so you don't have to explicitly point to the `dist` folder

**Comment by bigshiny90** [comment]
that worked for the import...

i'm not really getting anything happening though...  i'm wondering if the fact that i'm also using ngx-loading-bar:

https://github.com/aitboudad/ngx-loading-bar

which also has a httpclient module, which is probably some kind of interceptor.. might be interacting badly with BlockUIHttpModule...

certainly not your problem!  but let me know if you have any thoughts ;)

**Comment by kuuurt13** [comment]
@bigshiny90 I fixed how the package is bundled so now `import { BlockUIHttpModule } from 'ng-block-ui/http';` should work. 

As for working with https://github.com/aitboudad/ngx-loading-bar I had no problems getting them to work together. Checkout this example out for reference https://codesandbox.io/s/n1nlwjoql. Feel free to fork it and mess around to see if you can reproduce your issue and I would be more than happy to help.

**Comment by kuuurt13** [comment]
@bigshiny90 I played around with that codesandbox l created and I think I found the issue that you are seeing. For whatever reason the blocking is ending early even though the request is still pending. I will look into it and will try to get a fix out tonight.

**Comment by bigshiny90** [comment]
That's awesome you looked into it!  a big thanks to you, truly...  let me
know what you find ;)

-steve

**Comment by kuuurt13** [comment]
@bigshiny90 I believe I fixed the issue that you were seeing. Please update to `1.0.4`and give it a shot.

**Comment by kuuurt13** [comment]
Closing, feel free to open back up if you have issues
