### ISSUE TITLE
Add Angular 4.x Support

### ISSUE THREAD

**Issue by kuuurt13** [kuuurt13/ng-block-ui#6]
## Issue
Currently there is no support for 4.0, see #1. At the moment, Angular is on 4.0.0-RC.1 and 4.0.0 final is scheduled to officially release on [2017-03-22](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md). Unfortunately, building ng-block-ui for 4.x is not backwards compatible with 2.x.

## Proposal
Since the official release is a few weeks off and it will take a while for everyone to upgrade to 4.0. I think it would be best if a `next` tag was created in npm (this is what the angular team currently uses for future releases). I will be starting at 1.0.0-beta.0 and support 4.x. Any features/fixes added to the current version (0.3.0) will be added into this version. Once I feel like Angular 4.0 is being widely adopted I will point the npm `latest` tag to 1.0.0 so that will be the default when installing from npm.

**Comment by shuryyy** [comment]
Hi @kuuurt13 working for  4.0.0-RC.1.

Thanks !!

**Comment by kuuurt13** [comment]
@shuryyy, good to hear! If you have any other problems, feel free to open a new issue.
