### ISSUE TITLE
when building for prod mode, at runtime fails to inject. building in dev mode works.

### ISSUE THREAD

**Issue by geetee24** [kuuurt13/ng-block-ui#60]
AppComponent.html:3 ERROR Error: StaticInjectorError(AppModule)[BlockUIContentComponent -> BlockUIInstanceService]: 
  StaticInjectorError(Platform: core)[BlockUIContentComponent -> BlockUIInstanceService]: 
    NullInjectorError: No provider for BlockUIInstanceService!

Any idea why it fails in prod mode?

Thanks

**Comment by geetee24** [comment]
5.2.10 ng.
here is snuippet

import { BlockUIModule } from 'ng-block-ui';							// https://www.npmjs.com/package/ng-block-ui

@NgModule ( {
	imports: [
		BlockUIModule.forRoot(),
	],
	declarations: [
	],
	providers: [
	],
	entryComponents: [ BrcTestComponent, UrlOptionsModalDialogComponent, Olp2BlockUiLoadingTemplateComponent ],
	bootstrap: [ AppComponent ],

	schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
} )

export class AppModule {
}

**Comment by kuuurt13** [comment]
Thanks @geetee24! Your import looks fine, thanks for shating. I just tested a new app with angular cli (ng 5.2.10) and I had no issues running `ng build --prod` or `ng serve --prod` 🤔 

Looking closer at the error, it looks like the error is at `AppComponent.html:3`. Can you post your template from `AppComponent`. There might be something in there that is causing the issue?

**Comment by kuuurt13** [comment]
It might have something to do with your `blockUiTemplate` template. I can't reproduce the error with a Component/TemplateRef block ui template in prod mode. Can you give me more info on your block-ui template. The more of you code I can see the better I can help. If you have a repo I can look at or if you can add a simple version your to https://codesandbox.io/s/angular I can help a little more.

**Comment by geetee24** [comment]
<div class="block-ui-template" >
	<div class="container-fluid" >
		<div class="row justify-content-center" >
			<div class="col-8 col-sm-4 col-md-4 col-lg-3 col-xl-3" >
				<div class="sk-fading-circle" >
					<div class="sk-circle1 sk-circle" ></div>
					<div class="sk-circle2 sk-circle" ></div>
					<div class="sk-circle3 sk-circle" ></div>
					<div class="sk-circle4 sk-circle" ></div>
					<div class="sk-circle5 sk-circle" ></div>
					<div class="sk-circle6 sk-circle" ></div>
					<div class="sk-circle7 sk-circle" ></div>
					<div class="sk-circle8 sk-circle" ></div>
					<div class="sk-circle9 sk-circle" ></div>
					<div class="sk-circle10 sk-circle" ></div>
					<div class="sk-circle11 sk-circle" ></div>
					<div class="sk-circle12 sk-circle" ></div>
				</div>

				<div class="olp2blockUiLoadingMessage" > {{ message }}</div>
			</div>
		</div>
	</div>
</div>

Component(
	{
		selector: 'block-temp',
		styleUrls: [ './blockUiLoadingTemplate.component.scss' ],
		templateUrl: './blockUiLoadingTemplate.component.html'
	}
)


export class Olp2BlockUiLoadingTemplateComponent {
	
	public message : string = '';
	
	constructor() {
		
		console.logIn ( globalGst.debugConsoleControl.boolEnableBlockUiLoadingTemplateComponent, '', 'Olp2BlockUiLoadingTemplateComponent constr' );
		
		console.logOut ( globalGst.debugConsoleControl.boolEnableBlockUiLoadingTemplateComponent, '', 'Olp2BlockUiLoadingTemplateComponent constr' );
	}
	
}

**Comment by kuuurt13** [comment]
Hm I'm still not seeing anything out of the ordinary. I have a few other things to ask/try.

1. Does the error go away when you remove the custom template and use the default one? 
2. Do you still see the error when you set the custom template in the module `BlockUIModule.forRoot({ template: Olp2BlockUiLoadingTemplateComponent })`?
3. Can you try reinstalling ng-block-ui `npm uninstall ng-block-ui && npm install ng-block-ui@latest -S ` and see if it works?

**Comment by geetee24** [comment]
now even when i build in dev mode i get same error. any luck on your end?

**Comment by geetee24** [comment]
when (1) above : <block-ui [delayStop]="1000"  >

I still get the error.

ERROR Error: StaticInjectorError(AppModule)[BlockUIContentComponent -> BlockUIInstanceService]: 
  StaticInjectorError(Platform: core)[BlockUIContentComponent -> BlockUIInstanceService]: 
    NullInjectorError: No provider for BlockUIInstanceService!

(3) did not help.

**Comment by kuuurt13** [comment]
@geetee24 so I have been looking into this and still can't seem to reproduce the issue you are seeing. I'm thinking there might be something with your setup. To test this, I created an example repo with Angluar CLI that uses Angular 5.2.10 https://github.com/kuuurt13/ng-block-ui-example. 

I have tested this example and it builds/works fine with `ng serve` and `ng serve --prod`. Can you clone this repo, install the npm modules and try to run it? Let me know if runs for you because if so it would mean that the issue you are seeing is unique to your repo/setup.

**Comment by kuuurt13** [comment]
Closing for now due to lack of activity, feel free to open back up
