### ISSUE TITLE
Update to RxJS 6

### ISSUE THREAD

**Issue by pardamike** [kuuurt13/ng-block-ui#61]
RxJS 6.x has changed how we import its modules and operators, causing this package to throw some errors.  Should just be a matter of adjusting the imports:

ERROR in node_modules/ng-block-ui/lib/services/block-ui-instance.service.d.ts(1,10): error TS2305: Module '"C:/Dev/testblockui/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

Fixing this import gives way to more errors:

ERROR in ./node_modules/ng-block-ui/lib/services/block-ui-instance.service.js
Module not found: Error: Can't resolve 'rxjs/ReplaySubject' in 'C:\Dev\testblockui\node_modules\ng-block-ui\lib\services'
ERROR in ./node_modules/ng-block-ui/lib/components/block-ui-content/block-ui-content.component.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'C:\Dev\testblockui\node_modules\ng-block-ui\lib\components\block-ui-content'

package.json:
```
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "core-js": "^2.5.4",
    "ng-block-ui": "^1.0.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
```

Steps to reproduce:
```
ng new testblockui
npm install ng-block-ui --save
```

Add the import to app.module:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { BlockUIModule } from 'ng-block-ui'; 

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BlockUIModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Serve:
```
ng serve
```

App generated with Angular CLI:
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64

Note: edited several times for spelling and clarity

**Comment by pardamike** [comment]
FYI in case you have not seen it: https://www.academind.com/learn/javascript/rxjs-6-what-changed/

**Comment by pardamike** [comment]
Sorry I closed by accident.

**Comment by kuuurt13** [comment]
Thanks for reporting I appreciate all the details you provided. 

Yeah, I saw the changes in rxjs 6 but didn't realize that it wasn't backwards compatible right away. Looks like I might need to ship my library with https://www.npmjs.com/package/rxjs-compat. You can try to install `rxjs-compat` for the time being and see if that works for you for now.

I would like to migrate to rxjs 6 but if I do, I believe it will break the library for anyone on any version before rxjs 6. I need to put a little research into this to make sure.

**Comment by pardamike** [comment]
Using `rxjs-compat` now and it works perfect, thank you!

**Comment by kuuurt13** [comment]
Great, that is good to hear! I am going to keep this issue open since I still need to figure the best way to fix this and see what other libraries are doing. Not sure if I should ship my npm package with `rxjs-compat` as a dependency or not. Thanks again for reporting 👍

**Comment by Ludevik** [comment]
Hi @kuuurt13 , one option is to upgrade the code to rxjs and bump your version to 6 as well, so that consumers of this library know which version is compatible with which version of Angular.

**Comment by kuuurt13** [comment]
Hey @Ludevik, the only issue with that is I believe this library would no longer be backwards compatible for anyone who hasn't migrated to Angular 6 yet. I don't want to break functionality for < Angular 6.x users. I'm leaning towards shipping the package with https://www.npmjs.com/package/rxjs-compat as a dependency which would fix it for both Angular 6.x or less.

If you look at `rxjs-compat` and it looks like ~120 libraries are also including it as a dep.

**Comment by tamilsweet** [comment]
Please have version compatibility table instead of forcing to use rxjs-compat. Users with Angular < 6 can use ng-block-ui < 1.0.x or something and Angular 6+ users can use the latest version.

**Comment by kuuurt13** [comment]
@tamilsweet I'm working on it

**Comment by Ludevik** [comment]
@kuuurt13 need help? i can either implement it or at least try it on my project, this library is currently the only one from my dependencies that requires rxjs-compat

**Comment by kuuurt13** [comment]
@Ludevik I upgraded Angular/RxJS last night and everything seems to be okay (https://github.com/kuuurt13/ng-block-ui/commit/2599e8ad00b5e270d9ed91f2da490a1cca181271). I just want to smoke test everything one more time but I should have a `2.0.0` version with the changes out by this weekend.

**Comment by mlearncore2018** [comment]
@kuuurt13, I'm new to Angular 6 so pardon my layman question. I'm trying to use ng-block-ui and my project is being compiled successfully. Although, in my console, I'm getting the following error-
-----------------------------------------------------------------------------------------------
Uncaught Error: Template parse errors:
'block-ui' is not a known element:
1. If 'block-ui' is an Angular component, then verify that it is part of this module.
2. If 'block-ui' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </div>
        
        [ERROR ->]<block-ui>
            <h1>Customized Loading CSS</h1>
            <button class="control control__bt"): ng:///CoreModule/SearchContentComponent.html@11:8
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14702)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22709)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22696)
    at compiler.js:22639
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22639)
    at compiler.js:22549
    at Object.then (compiler.js:206)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)
syntaxError @ compiler.js:215
push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse @ compiler.js:14702
push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate @ compiler.js:22709
push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate @ compiler.js:22696
(anonymous) @ compiler.js:22639
push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents @ compiler.js:22639
(anonymous) @ compiler.js:22549
then @ compiler.js:206
push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents @ compiler.js:22548
push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync @ compiler.js:22508
push../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:143
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:4790
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:76
0 @ main.ts:12
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1

-------------------------------------------------------------------------------------------------

I've checked my ng-block-ui version and it is 1.0.5
Will updating to the 2.0.0 resolve this issue?

**Comment by kuuurt13** [comment]
@mlearncore2018 I'm going to take a guess that you haven't imported the `BlockUIModule` into your apps `NgModule`. Please make sure you have it imported like below.

```
import { BlockUIModule } from 'ng-block-ui';

@NgModule({
  imports: [
    BlockUIModule.forRoot()
  ],
  ... // The rest of your NgModule
})
export class AppModule { }
```

**Comment by kuuurt13** [comment]
I have published `ng-block-ui@2.0.0-beta.1` which adds support for Angular 6 and RXjs 6. Please install (`npm i - S ng-block-ui@next`) and try it out in your Angular 6. Let me know if any of you run into any issues.

**Comment by Ludevik** [comment]
thanks, it works, i have updated to 2.0.0 and got rid of rxjs-compat 🥇

**Comment by rahul20diatm** [comment]
block-ui directive is not working even when i have imported the block-ui module in app module

**Comment by kuuurt13** [comment]
@rahul20diatm may I ask why you think your issue is related to upgrading to rxjs 6? 

Also, can you please include more info like any errors you are seeing or at the very least the specific version of Angular and ng-block-ui you are using?

In the mean time, here is an app with an directive example which is 100% working which uses Angular 6, rxjs 6 and `ng-block-ui@2.0.0-beta.2` https://stackblitz.com/github/kuuurt13/ng-block-ui/tree/next/examples/directive?file=src%2Fapp%2Fapp.component.html

**Comment by rahul20diatm** [comment]
@kuuurt13 i get following error.
Can't bind to 'blockUI' since it isn't a known property of 'div'. ("="'General.Loading' | translate"></app-progress-bar>
<div class="container">
    <div class="row" [ERROR ->]*blockUI="'test'">
I have imported blockui module in root module(app.module.ts) . My app component looks like
<block-ui>
  <app-body>
    <ng-template>
      <div class="content">
        <router-outlet></router-outlet>
      </div>    
    </ng-template>
  </app-body>
</block-ui>

Now i have report module inside my app.module. This report module has report component where i am using *blockUI directive on div  there it throws error.

If I  remove the *blockUI directive and use the complete page level blocking technique it works fine.

**Comment by Ludevik** [comment]
@rahul20diatm you need to import `BlockUIModule` (without .forRoot()) in your ReportModule too. Everything that the module depends on must be imported in that module.

**Comment by mjschranz** [comment]
@tamilsweet has the correct idea here. Do we have any updates timelines on when we can expect this? I'd like to drop support for `rxjs-compat` from my project and this is the last module using it.

**Comment by kuuurt13** [comment]
@mjschranz you can update to`ng-block-ui@2.0.0-beta.2` right now and it will work without `rxjs-compat` as stated in the comments above. I am also going to roll out the official `2.0.0` release this weekend as well.
