### ISSUE TITLE
Move Code Examples Off of Plunker

### ISSUE THREAD

**Issue by kuuurt13** [kuuurt13/ng-block-ui#62]
Plunker seems to be getting more and more unstable. All code examples in documentation should be moved to a different code sandbox.

**Comment by Ludevik** [comment]
@kuuurt13 hi, i could help with this. I suggest to move the examples to stackblitz. I created demo for the first example: [https://ng-block-ui-component.stackblitz.io](https://ng-block-ui-component.stackblitz.io). I can move the other examples too, if you agree. What do you think?

**Comment by Ludevik** [comment]
So now the examples are moved to Stackblitz. Next step would be to automatically generate examples from the repository itself. I'll try to do this as well.

**Comment by Ludevik** [comment]
Yea, there are multiple ways how to do it in stackblitz. You can host the github angular cli project too - [https://stackblitz.com/github/kuuurt13/ng-block-ui-example/tree/master/](https://stackblitz.com/github/kuuurt13/ng-block-ui-example/tree/master/), just like on codesandbox. Angular.io and angular material both use stackblitz now for their examples, so i guess they made some research before selecting the tool. So my recommendation is to just use the tool they chosen and maybe look into their sources how they leverage stackblitz to provide examples.

**Comment by kuuurt13** [comment]
That works for me. Thanks for looking into this!

It looks like I can also point to a sub folder and run it on [stackblitz](https://stackblitz.com/github/kuuurt13/ng-block-ui/tree/next/examples/default) as well. I have a WIP branch with some of the examples added into a `examples` folder https://github.com/kuuurt13/ng-block-ui/tree/next/examples. I will finish this up and get it in for the `2.0.0` release. Thanks again for the help!

**Comment by kuuurt13** [comment]
Moved all examples into the repo, closing this. Thanks again for all the help @Ludevik
