### ISSUE TITLE
Allow modification of styles in block-ui-wrapper class

### ISSUE THREAD

**Issue by talhajunaidd** [kuuurt13/ng-block-ui#65]
Please allow modification of styles in `block-ui-wrapper` class. when using custom template
Currently I've faced a scenario where I need to use lighter color and lower z-index value
```
.block-ui-wrapper {
    background: rgba(0, 0, 0, 0.70);
    z-index: 30000
 }
```
But due to these I can't change the color.

**Comment by kuuurt13** [comment]
This is already possible. There is an example directly in the docs on how to do this https://github.com/kuuurt13/ng-block-ui#blockui-custom-spinner-styles---plunker and a past issue https://github.com/kuuurt13/ng-block-ui/issues/16. You need to set a higher CSS specificity on the wrapper for your changes to take effect.

**Comment by talhajunaidd** [comment]
Alright. got it. Thanks @kuuurt13
