### ISSUE TITLE
StaticInjectorError with Angular universal server side rendering

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [kuuurt13/ng-block-ui#79]
Hi,

I'm upgrading an Angular Universal project to the latest Angular version and I get errors with the ng-block-ui version 2.0.0-beta2. It worked fine with Angular 4 and ng-block-ui 1.0.6. Steps to reproduce:

1. `git clone https://github.com/angular/universal-starter.git`.
2. `npm i`.
3. `npm i --save ng-block-ui@next`.
4. Add ng-block-ui as described in the docs.
5. `npm run build:ssr && npm run serve:ssr`.
6. Open http://localhost:4000.

Result: I get the following error:

`Error: StaticInjectorError(AppServerModule)[BlockUIContentComponent -> BlockUIInstanceService]: 
  StaticInjectorError(Platform: core)[BlockUIContentComponent -> BlockUIInstanceService]: 
    NullInjectorError: No provider for BlockUIInstanceService!`

I created a demo repository in https://github.com/SoftwareAndOutsourcing/universal-starter-ng-block-ui-demo following the above steps.

Thanks.

**Comment by kuuurt13** [comment]
@SoftwareAndOutsourcing thank you for making this issue so detailed and providing an example, it is appreciated! 👏 

I will take a deep dive into this issue this weekend. I'm thinking this is coming from changes in Angular Universal/Angular because I haven't changed anything drastic with the module or the providers since `1.0.6` so not sure why this would break 🤔. It might be something with how I am building/distributing the library that worked for Angular 4 and not Angular 5/6. I have had issue with something like that in the past with AOT.

**Comment by kuuurt13** [comment]
@SoftwareAndOutsourcing so it looks like it is an issue with how I am packaging the library. I ended up using https://github.com/dherges/ng-packagr which follows Angular's APF standard for packaging libraries and it worked in your example repo. I still need to test a few things with the new packager but I should be able to have a new version out in the next day or two.

**Comment by SoftwareAndOutsourcing** [comment]
@kuuurt13 thanks for the prompt response.

Angular CLI 6 includes support for libraries using ng-packagr, maybe migrating to it will provide an easier way to upgrade to future versions: https://github.com/angular/angular-cli/wiki/stories-create-library.

**Comment by kuuurt13** [comment]
Yeah, it might make sense to add in Angular CLI in the future. When I first created the library the CLI was lacking from a library author standpoint, this looks promising though!

I published a new version `ng-block-ui@2.0.0-beta.3` that is working for me in the Angular Universal test repo you shared. Give it a shot and let me know if you have any issues.

**Comment by SoftwareAndOutsourcing** [comment]
I tried 2.0.0-beta.3 and seems it's working fine. Thanks again for your help.
