### ISSUE TITLE
Issue with observable in version 1.0.6

### ISSUE THREAD

**Issue by bdairy** [kuuurt13/ng-block-ui#81]
ERROR in node_modules/ng-block-ui/lib/services/block-ui-instance.service.d.ts(1,10): error TS2305: Module '"C:/...//node_modules/rxjs/Observable"' has
no exported member 'Observable'.

Unable to run my application

**Comment by kuuurt13** [comment]
@bdairy sounds like you are using Angular 6/rxjs 6. Please see #61
