### ISSUE TITLE
blockAllRequestsInProgress setting missing from 2.1.1?

### ISSUE THREAD

**Issue by symlynk** [kuuurt13/ng-block-ui#93]
npm is showing 2.1.1 is installed of ng-block-ui, but the setting blockAllRequestsInProgress is missing for the http module.

**Comment by kuuurt13** [comment]
@symlynk I tried with a fresh install and I see the `blockAllRequestsInProgress` setting. I'm not sure why you are having issues but I can't seem to reproduce. Can you try to reinstall and restart your IDE?

![image](https://user-images.githubusercontent.com/11655463/52603418-bcaad480-2e34-11e9-891d-07f6ed50a2a0.png)

**Comment by symlynk** [comment]
Thanks - I have created a new project, and the setting is there - it's something to do with my existing project. Will investigate further.

**Comment by kuuurt13** [comment]
Okay, going to close then. Feel free to open an issue if you investigate and find an issue with the library.
